"use strict";
console.log("hey abu hurairah, i have started learning typscript ");
var Name = "fatima";
console.log(Name);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var sum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log(sum);
var mins = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
console.log(mins);
var multiply = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log(multiply);
var divide = num10 / num5;
console.log(divide);
